# Generated by Django 6.0.1 on 2026-01-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=165)),
                ('cover', models.ImageField(blank=True, default='', upload_to='recipes/covers/%Y/%m/%d/')),
            ],
        ),
    ]
