# Generated by Django 6.0.1 on 2026-01-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(blank=True, default='', upload_to='jhones/covers/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='sectionprojects',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='jhones/covers/%Y/%m/%d/'),
        ),
    ]
