# Generated by Django 6.0.1 on 2026-01-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhones', '0002_skills_alter_sectionprojects_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=165)),
            ],
        ),
    ]
