# Generated by Django 6.0.1 on 2026-01-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhones', '0003_myservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('icon', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=265)),
            ],
        ),
        migrations.AlterField(
            model_name='myservices',
            name='description',
            field=models.CharField(max_length=265),
        ),
    ]
