# Generated by Django 6.0.1 on 2026-01-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jhones', '0004_contact_alter_myservices_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Social',
        ),
    ]
