# Generated by Django 6.0.1 on 2026-01-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhones', '0005_rename_contact_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionprojects',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
