# Generated by Django 6.0.2 on 2026-02-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhones', '0006_sectionprojects_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionprojects',
            name='text',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
